defmodule EctoRedshift.Schema do
  @moduledoc """
  Redshift-friendly schema defaults for Ecto.

  Amazon Redshift does not support `RETURNING`, so database-generated integer
  primary keys are awkward to use with the normal `Repo.insert/2` flow —
  Ecto cannot read the generated ID back after an insert. This macro sets
  application-generated binary IDs (UUIDs, autogenerated client-side) as the
  default primary and foreign key strategy, avoiding the problem entirely.

  It is a thin wrapper around `use Ecto.Schema` that sets two module
  attributes:

      @primary_key {:id, :binary_id, autogenerate: true}
      @foreign_key_type :binary_id

  ## Example

      defmodule MyApp.Analytics.Event do
        use EctoRedshift.Schema

        schema "events" do
          field :kind, :string
          field :payload, :map
          belongs_to :account, MyApp.Accounts.Account
          timestamps()
        end
      end

  ## Options

    * `:primary_key` — overrides the default primary key tuple. Pass `false`
      to disable entirely. Defaults to `{:id, :binary_id, autogenerate: true}`.
    * `:foreign_key_type` — overrides the default foreign key type. Defaults
      to `:binary_id`.

  ## Opting out

  If you need a different primary key strategy for a specific schema, just
  use `Ecto.Schema` directly:

      defmodule MyApp.Metrics.RawEvent do
        use Ecto.Schema

        @primary_key false
        schema "raw_events" do
          # ...
        end
      end
  """

  defmacro __using__(opts \\ []) do
    primary_key = Keyword.get(opts, :primary_key, {:id, :binary_id, autogenerate: true})
    foreign_key_type = Keyword.get(opts, :foreign_key_type, :binary_id)

    quote do
      use Ecto.Schema

      @primary_key unquote(Macro.escape(primary_key))
      @foreign_key_type unquote(foreign_key_type)
    end
  end
end
