defmodule Ecto.Adapters.Redshift.DDLTest do
  use ExUnit.Case, async: true

  import Ecto.Migration

  defp sqls(statements) do
    Enum.map(statements, &IO.iodata_to_binary/1)
  end

  test "creates tables with Redshift-specific options" do
    ddl =
      Ecto.Adapters.Redshift.Connection.execute_ddl(
        {:create,
         table("events",
           comment: "event log",
           options: [
             backup: false,
             diststyle: :key,
             distkey: :account_id,
             sortkey: {:interleaved, [:occurred_at, :account_id]},
             encode: :auto
           ]
         ),
         [
           {:add, :id, :identity, [primary_key: true]},
           {:add, :account_id, :bigint, [null: false, encode: :az64]},
           {:add, :payload, :super, [null: false, encode: :zstd, comment: "raw event"]},
           {:add, :occurred_at, :naive_datetime_usec, []}
         ]}
      )

    assert sqls(ddl) == [
             ~s|CREATE TABLE "events" ("id" bigint GENERATED BY DEFAULT AS IDENTITY, "account_id" bigint ENCODE AZ64 NOT NULL, "payload" super ENCODE ZSTD NOT NULL, "occurred_at" timestamp, PRIMARY KEY ("id")) BACKUP NO DISTSTYLE KEY DISTKEY("account_id") INTERLEAVED SORTKEY("occurred_at","account_id") ENCODE AUTO|,
             ~s|COMMENT ON TABLE "events" IS 'event log'|,
             ~s|COMMENT ON COLUMN "events"."payload" IS 'raw event'|
           ]
  end

  test "supports explicit super columns while keeping map columns conservative" do
    ddl =
      Ecto.Adapters.Redshift.Connection.execute_ddl(
        {:create, table("documents"),
         [
           {:add, :metadata, :map, []},
           {:add, :payload, :super, [default: %{kind: "note"}]}
         ]}
      )

    assert sqls(ddl) == [
             ~s|CREATE TABLE "documents" ("metadata" varchar(max), "payload" super DEFAULT JSON_PARSE('{"kind":"note"}'))|
           ]
  end

  test "alters tables through Redshift-supported clauses" do
    ddl =
      Ecto.Adapters.Redshift.Connection.execute_ddl(
        {:alter, table("events"),
         [
           {:add_if_not_exists, :tenant_id, :bigint,
            [encode: :az64, null: false, comment: "tenant id"]},
           {:modify, :title, :string, [size: 1024]},
           {:modify, :payload, :string, [encode: :zstd]},
           {:remove_if_exists, :legacy_payload}
         ]}
      )

    assert sqls(ddl) == [
             ~s|ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "tenant_id" bigint ENCODE AZ64 NOT NULL|,
             ~s|ALTER TABLE "events" ALTER COLUMN "title" TYPE varchar(1024)|,
             ~s|ALTER TABLE "events" ALTER COLUMN "payload" ENCODE ZSTD|,
             ~s|ALTER TABLE "events" DROP COLUMN IF EXISTS "legacy_payload"|,
             ~s|COMMENT ON COLUMN "events"."tenant_id" IS 'tenant id'|
           ]
  end

  test "drops named constraints" do
    ddl =
      Ecto.Adapters.Redshift.Connection.execute_ddl(
        {:drop, constraint("events", "events_account_id_fkey"), :cascade}
      )

    assert sqls(ddl) == [
             ~s|ALTER TABLE "events" DROP CONSTRAINT "events_account_id_fkey" CASCADE|
           ]
  end

  test "rejects indexes because Redshift has no index support" do
    assert_raise ArgumentError, ~r/does not support indexes/, fn ->
      Ecto.Adapters.Redshift.Connection.execute_ddl({:create, index("events", [:occurred_at])})
    end
  end

  test "rejects unsupported table options" do
    assert_raise ArgumentError, ~r/unsupported Redshift table options/, fn ->
      Ecto.Adapters.Redshift.Connection.execute_ddl(
        {:create, table("events", options: [foo: :bar]), []}
      )
    end
  end

  test "rejects unsupported alter-table reference additions" do
    reference = %Ecto.Migration.Reference{table: "accounts"}

    assert_raise ArgumentError, ~r/references is not supported/, fn ->
      Ecto.Adapters.Redshift.Connection.execute_ddl(
        {:alter, table("events"), [{:add, :account_id, reference, []}]}
      )
    end
  end
end
