defmodule Ecto.Adapters.Redshift.SchemaSupportTest do
  use ExUnit.Case, async: true

  defmodule IntegerIdEvent do
    use Ecto.Schema

    schema "events" do
      field(:status, :string)
    end
  end

  defmodule BinaryIdAccount do
    use EctoRedshift.Schema

    schema "accounts" do
      field(:name, :string)
    end
  end

  defmodule BinaryIdEvent do
    use EctoRedshift.Schema

    schema "events" do
      field(:payload, :map)
      belongs_to(:account, BinaryIdAccount)
    end
  end

  test "rejects autogenerated integer primary keys on insert with a clear error" do
    schema_meta = %{
      autogenerate_id: IntegerIdEvent.__schema__(:autogenerate_id),
      context: nil,
      prefix: nil,
      schema: IntegerIdEvent,
      source: "events"
    }

    assert_raise ArgumentError, ~r/cannot read back autogenerated :id primary keys/, fn ->
      Ecto.Adapters.Redshift.insert(
        %{},
        schema_meta,
        [status: "queued"],
        {:raise, [], []},
        [:id],
        []
      )
    end
  end

  test "rejects returning-based schema updates clearly" do
    schema_meta = %{
      autogenerate_id: BinaryIdEvent.__schema__(:autogenerate_id),
      context: nil,
      prefix: nil,
      schema: BinaryIdEvent,
      source: "events"
    }

    assert_raise ArgumentError, ~r/does not support RETURNING for update/, fn ->
      Ecto.Adapters.Redshift.update(
        %{},
        schema_meta,
        [payload: %{"kind" => "click"}],
        [id: Ecto.UUID.generate()],
        [:updated_at],
        []
      )
    end
  end

  test "rejects schema upserts before reaching SQL execution" do
    schema_meta = %{
      autogenerate_id: BinaryIdEvent.__schema__(:autogenerate_id),
      context: nil,
      prefix: nil,
      schema: BinaryIdEvent,
      source: "events"
    }

    assert_raise ArgumentError, ~r/does not support :on_conflict upserts yet/, fn ->
      Ecto.Adapters.Redshift.insert(
        %{},
        schema_meta,
        [id: Ecto.UUID.generate(), payload: %{"kind" => "click"}],
        {:nothing, [], []},
        [],
        []
      )
    end
  end

  test "EctoRedshift.Schema defaults schemas to binary ids" do
    assert BinaryIdAccount.__schema__(:type, :id) == :binary_id
    assert BinaryIdEvent.__schema__(:type, :id) == :binary_id
    assert BinaryIdEvent.__schema__(:type, :account_id) == :binary_id
    assert BinaryIdEvent.__schema__(:autogenerate_id) == {:id, :id, :binary_id}
  end
end
